In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
b = np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [6]:
print(b[0][0])

1


In [8]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c[1][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [9]:
#transpose of a matrix
print(c.T)

[[1 4]
 [2 5]
 [3 6]]


You can pass -1 for a dimension and NumPy can
infer the correct dimension based on your matrix:

In [10]:
# Create zeros, ones, custom arrays
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
b = np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
c = np.full((3,2),5)
print(c)

[[5 5]
 [5 5]
 [5 5]]


In [14]:
#Identity matrix
d = np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
#random matrix
randomMatrix = np.random.random((2,3))
print(randomMatrix)

[[0.88809704 0.45247493 0.10352314]
 [0.71981226 0.25821672 0.11153646]]


In [16]:
print(randomMatrix[ : ,2])

[0.10352314 0.11153646]


In [18]:
randomMatrix[1,1:3] = 1
print(randomMatrix)

[[0.88809704 0.45247493 0.10352314]
 [0.71981226 1.         1.        ]]


In [20]:
# Set some rows and columns with any values
z = np.zeros((3,3), dtype=np.int64)
print(z)
z[1,:]=5
z[:,-1]=7
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [21]:
# Mathematical Operations

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

#Element wise Addition
print(x+y)
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [22]:
print(x-y)
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [23]:
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [25]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [26]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [27]:
print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [36]:
# Multiplication of vectors => Scalar
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b))


30


In [29]:
print(a)

[1 2 3 4]


In [30]:
print(sum(a))

10


In [31]:
print(x)

[[1 2]
 [3 4]]


In [32]:
print(np.sum(x))
print(np.sum(x,axis=0))

10
[4 6]


In [33]:
print(np.sum(x,axis=1))

[3 7]


In [37]:
a = np.stack((a,b),axis=0)
print(a)

[[1 2 3 4]
 [1 2 3 4]]


In [38]:
# reshape a numpy array
a = a.reshape((4,2))
print(a)

[[1 2]
 [3 4]
 [1 2]
 [3 4]]


In [41]:
# suppose you  only know the no of columns to be 4 then put x=-1 so that computer will automatically calculate the value of x
a = a.reshape((-1,4))
print(a)

[[1 2 3 4]
 [1 2 3 4]]


# Numpy Random Module

- rand : random values in a given shape
- randn : return a sample from the "standard normal" distribution 
- randint : return random integers from low(inclusive) to high(exclusive)
- random : return random floats in the half-open interval \[0.0, 1.0)  
- choice : generates a random sample from a given 1-D array
- shuffle : shuffles the contents of a sequence

In [42]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [45]:
np.random.shuffle(a)
print(a)

[ 5 12 10  8  6 11 14  7 13  9]


In [57]:
a = np.random.rand(2,3)
print(a)

[[7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01]]


In [58]:
np.random.seed(1)
np.random.shuffle(a)
print(a)

[[7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01]]


In [53]:
# returns values from a standard normal distribution
a = np.random.randn(2,3)
print(a)

[[-0.43838807 -0.02295837  0.69871184]
 [-1.55921614  0.93727386  0.89730101]]


In [54]:
# range - 5 to 10, no of numbers = 3
a = np.random.randint(5,10,3)
print(a)

[5 9 7]


In [55]:
# randomly pick one element from a array
element = np.random.choice([1,4,3,2,11,27])
print(element)

11


# Some more Numpy Functions - Statistics
- min, max
- mean
- median
- average
- variance
- standard deviation

In [4]:
a = np.array([[1,2,3,4],[7,6,2,0]])
print(a)
print(np.min(a))
# Specify axis for the direction in case of multidimensional array
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]


In [5]:
b = np.array([1,2,3,4,5])
m = sum(b)/5
print(m)

print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [7]:
c = np.array([1,5,4,2,0])
print(np.median(c))

# Mean vs Average (average is weigyhted)
print(np.median(c))

w = np.array([1,2,3,4,5])
print(np.average(c,weights=w))

2.0
2.0
2.066666666666667


In [9]:
# Standard Deviation
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

#Inbuilt Function
dev = np.std(c)
print(dev)

1.854723699099141
1.854723699099141


In [10]:
#Variance
print(myStd**2)
print(np.var(c))

3.440000000000001
3.4400000000000004
